sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - DEPS=latest

before_install:
  - shopt -s expand_aliases
  - alias composer="travis_retry docker-compose run --rm php composer"
  - alias php="travis_retry docker-compose run -e TRAVIS -e TRAVIS_JOB_ID --rm php php"
  - docker-compose build --build-arg PHP_VERSION=${TRAVIS_PHP_VERSION} --build-arg XDEBUG=${TEST_COVERAGE:+1} --no-cache php
  - composer --version
  - php -v
  - php -m

install:
  - php --info
  - composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $LEGACY_DEPS != '' ]]; then composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - composer require --dev $COMPOSER_ARGS 
  - composer install $COMPOSER_ARGS
  - stty cols 120 && composer show
  - composer show

script:
  - cp ./tests/TestConfiguration.php ./config/application.config.php
  - ./vendor/bin/doctrine-module odm:schema:create
  - ./vendor/bin/doctrine-module odm:schema:drop
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/phpunit --coverage-clover clover.xml ; else php vendor/bin/phpunit ; fi
  - if $CHECK_CS; then php vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/ ./config/ ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/php-coveralls -v ; fi
